// All About Coding - Video Database
// This file contains all the video data for the website.

const videoData = [
  // JavaScript
  {
    videoId: "cpoXLj24BDY",
    category: "js",
    subCategory: "beginner",
    title: "🚀 🔥 JavaScript Complete Course (2024) 4 Projects | Notes | GitHub | Free Certification",
    views: "1.2M",
    date: "2024-05-15",
    duration: "4:20:15",
  },
  {
    videoId: "ajdRvxDWH4w",
    category: "js",
    subCategory: "beginner",
    title: "JavaScript Full Course ❤️ | Variables & Data Types | Lecture 1",
    views: "850K",
    date: "2024-04-20",
    duration: "1:15:30",
  },
  {
    videoId: "Zg4-uSjxosE",
    category: "js",
    subCategory: "beginner",
    title: "Lecture 2: Operators and Conditional Statements | JavaScript Full Course",
    views: "620K",
    date: "2024-04-22",
    duration: "1:05:45",
  },
  {
    videoId: "UmRtFFSDSFo",
    category: "js",
    subCategory: "beginner",
    title: "Lecture 3: Loops and Strings | JavaScript Full Course",
    views: "580K",
    date: "2024-04-25",
    duration: "1:10:20",
  },
  {
    videoId: "gFWhbjzowrM",
    category: "js",
    subCategory: "beginner",
    title: "Lecture 4: Arrays | JavaScript Full Course",
    views: "520K",
    date: "2024-04-28",
    duration: "1:05:10",
  },
  {
    videoId: "P0XMXqDGttU",
    category: "js",
    subCategory: "beginner",
    title: "Lecture 5: Functions & Methods | JavaScript Full Course",
    views: "480K",
    date: "2024-05-01",
    duration: "1:15:40",
  },
  {
    videoId: "7zcXPCt8Ck0",
    category: "js",
    subCategory: "advanced",
    title: "Lecture 6: DOM - Document Object Model | JavaScript Full Course | Part 1",
    views: "450K",
    date: "2024-05-05",
    duration: "1:20:15",
  },
  {
    videoId: "fXAGTOZ25H8",
    category: "js",
    subCategory: "advanced",
    title: "Lecture 7 : DOM (Part 2) | Document Object Model | JavaScript Full Course",
    views: "580K",
    date: "2024-05-08",
    duration: "1:10:20",
  },
  {
    videoId: "_i-uLJAh79U",
    category: "js",
    subCategory: "advanced",
    title: "Lecture 8: Events in JavaScript | JavaScript Full Course",
    views: "420K",
    date: "2024-05-10",
    duration: "1:10:30",
  },
  {
    videoId: "SqrppLEljkY",
    category: "js",
    subCategory: "project",
    title: "Lecture 9: Tic Tac Toe Game in JavaScript | JS Project",
    views: "380K",
    date: "2024-05-12",
    duration: "1:30:45",
  },
  {
    videoId: "_V33HCZWLDQ",
    category: "js",
    subCategory: "project",
    title: "Lecture 10: MiniProject - Stone, Paper & Scissors Game | JavaScript Full Course",
    views: "350K",
    date: "2024-05-14",
    duration: "1:15:20",
  },
  {
    videoId: "N-O4w6PynGY",
    category: "js",
    subCategory: "advanced",
    title: "Lecture 11: Classes & Objects | JavaScript Full Course",
    views: "320K",
    date: "2024-05-18",
    duration: "1:05:50",
  },
  {
    videoId: "d3jXofmQm44",
    category: "js",
    subCategory: "advanced",
    title: "Lecture 12: Callbacks, Promises & Async Await | JavaScript Full Course",
    views: "310K",
    date: "2024-05-20",
    duration: "1:25:30",
  },
  {
    videoId: "CyGodpqcid4",
    category: "js",
    subCategory: "advanced",
    title: "Last Lecture: Fetch API with Project | JavaScript Full Course",
    views: "290K",
    date: "2024-05-25",
    duration: "1:40:15",
  },
  {
    videoId: "yN2yBmSHduI",
    category: "js",
    subCategory: "beginner",
    title: "5 JavaScript Mistakes Every Beginner Must Avoid 🔥",
    views: "950K",
    date: "2024-05-16",
    duration: "0:15:30",
  },

  // CSS
  {
    videoId: "sqJ6xZ9mUwE",
    category: "css",
    subCategory: "beginner",
    title: "CSS - What is selectors? | Web Development Course",
    views: "620K",
    date: "2024-03-10",
    duration: "0:45:20",
  },
  {
    videoId: "4nC4VXHlys8",
    category: "css",
    subCategory: "beginner",
    title: "Properties in CSS | Web Development Course | CSS Lecture 2",
    views: "580K",
    date: "2024-03-12",
    duration: "0:55:30",
  },
  {
    videoId: "C01LeeMhwHc",
    category: "css",
    subCategory: "beginner",
    title: "Understanding Box Model | Styling List and Tables | CSS Lecture 3",
    views: "540K",
    date: "2024-03-15",
    duration: "0:50:15",
  },
  {
    videoId: "wKPlQkOdpFQ",
    category: "css",
    subCategory: "advanced",
    title: "Understanding Cascading , Specificity and Inheritance | CSS Lecture 4",
    views: "500K",
    date: "2024-03-18",
    duration: "0:45:40",
  },
  {
    videoId: "6Cpd63_WXdI",
    category: "css",
    subCategory: "beginner",
    title: "Styling Forms in CSS | Web Development Course | Lecture 5",
    views: "460K",
    date: "2024-03-20",
    duration: "0:40:25",
  },
  {
    videoId: "l-EkcthUMl4",
    category: "css",
    subCategory: "advanced",
    title: "Debugging in CSS | Web Development Course",
    views: "420K",
    date: "2024-03-22",
    duration: "0:35:50",
  },
  {
    videoId: "p870o46o1bM",
    category: "css",
    subCategory: "advanced",
    title: "What is Responsiveness? CSS | Web Development Course | Lecture 7",
    views: "380K",
    date: "2024-04-01",
    duration: "0:50:30",
  },
  {
    videoId: "xpoWxFyGuC8",
    category: "css",
    subCategory: "advanced",
    title: "Floats & Position Properties | CSS | Web Development Course",
    views: "350K",
    date: "2024-04-05",
    duration: "0:45:20",
  },
  {
    videoId: "zts6uNVnCNs",
    category: "css",
    subCategory: "advanced",
    title: "Learn Flexbox Under 25mins | Web Development Course",
    views: "320K",
    date: "2024-04-08",
    duration: "0:25:00",
  },
  {
    videoId: "xBSlwwitD5U",
    category: "css",
    subCategory: "advanced",
    title: "CSS Grid | Web Development Course",
    views: "300K",
    date: "2024-04-10",
    duration: "0:30:15",
  },
  {
    videoId: "Xdhdgl0Ju4k",
    category: "css",
    subCategory: "advanced",
    title: "Learn Animations in CSS",
    views: "280K",
    date: "2024-04-15",
    duration: "0:35:40",
  },
  {
    videoId: "IZa8pbR8CWs",
    category: "css",
    subCategory: "project",
    title: "Adding CSS to Mega Project",
    views: "260K",
    date: "2024-04-18",
    duration: "1:20:30",
  },
  {
    videoId: "ywK_wgQwKJY",
    category: "css",
    subCategory: "project",
    title: "Updating Design of Mega Project | Web Development Course",
    views: "240K",
    date: "2024-04-25",
    duration: "1:15:20",
  },
  {
    videoId: "DUiYVJIVNcA",
    category: "css",
    subCategory: "beginner",
    title: "Namaste World in Bootstrap | Web Development Course",
    views: "220K",
    date: "2024-04-28",
    duration: "0:40:15",
  },
  {
    videoId: "ddWKdSS5TaQ",
    category: "css",
    subCategory: "advanced",
    title: "Customization & Layout in Bootstrap | Web Development Course | Lecture 15",
    views: "200K",
    date: "2024-05-02",
    duration: "0:45:30",
  },
  {
    videoId: "5NxYn0GiApg",
    category: "css",
    subCategory: "advanced",
    title: "Bootstrap - Grid Layout | Web Development Course | Lecture 16",
    views: "180K",
    date: "2024-05-05",
    duration: "0:35:25",
  },
  {
    videoId: "IwlAhfeSnp8",
    category: "css",
    subCategory: "advanced",
    title: "Bootstrap - Components | Web Development Course | Lecture 17",
    views: "160K",
    date: "2024-05-10",
    duration: "0:50:40",
  },

  // HTML
  {
    videoId: "HcOc7P5BMi4",
    category: "html",
    subCategory: "beginner",
    title: "HTML Tutorial for Beginners | Complete HTML with Notes & Code",
    views: "1.5M",
    date: "2024-02-15",
    duration: "3:45:20",
  },
  {
    videoId: "Rek0NWPCNOc",
    category: "html",
    subCategory: "beginner",
    title: "HTML Course | From Beginners to Advance Level | Lecture 1",
    views: "850K",
    date: "2024-03-01",
    duration: "1:20:15",
  },
  {
    videoId: "2QR11oDukn4",
    category: "html",
    subCategory: "beginner",
    title: "HTML Course | World's most premium HTML Course | Lecture 2",
    views: "780K",
    date: "2024-03-05",
    duration: "1:30:40",
  },
  {
    videoId: "jRAZlTEZi9I",
    category: "html",
    subCategory: "beginner",
    title: "HTML Course | Media Elements | Lecture 3",
    views: "720K",
    date: "2024-03-10",
    duration: "1:15:30",
  },
  {
    videoId: "61ppyY5rUB0",
    category: "html",
    subCategory: "project",
    title: "HTML | Structuring a Mega Project",
    views: "650K",
    date: "2024-04-12",
    duration: "2:10:25",
  },

  // Other
  {
    videoId: "b7ttYWrJzCI",
    category: "other",
    subCategory: "career",
    title: "You can do much more with AI 🔥",
    views: "680K",
    date: "2024-05-01",
    duration: "0:12:30",
  },
  {
    videoId: "vQcHPQJ4Ujs",
    category: "other",
    subCategory: "career",
    title: "Which one to Choose - Web Development vs App Development ?",
    views: "870K",
    date: "2024-05-28",
    duration: "0:14:10",
  },
  {
    videoId: "RNh8VHc8qkk",
    category: "other",
    subCategory: "career",
    title: "All about Digital Marketing | Simply Explained",
    views: "520K",
    date: "2024-05-28",
    duration: "0:16:30",
  },
  {
    videoId: "Zff3rUY0iGg",
    category: "other",
    subCategory: "career",
    title: "How to Study MORE in LESS TIME 🔥 | 5 Principles | for students",
    views: "1.3M",
    date: "2024-05-29",
    duration: "0:13:45",
  },

  // Docker
  {
    videoId: "H8Lyj2D_cWo",
    category: "docker",
    subCategory: "beginner",
    title: "What is Docker? Simply Explained",
    views: "850K",
    date: "2024-05-15",
    duration: "0:15:30",
  },
  {
    videoId: "a-nWPre5QYI",
    category: "docker",
    subCategory: "advanced",
    title: "What is Kubernetes? | Kubernetes Explained",
    views: "720K",
    date: "2024-05-22",
    duration: "0:18:45",
  },
  {
    videoId: "exmSJpJvIPs",
    category: "docker",
    subCategory: "beginner",
    title: "Docker Tutorial for beginners - Complete One Shot",
    views: "650K",
    date: "2024-05-25",
    duration: "3:20:15",
  },

  // MERN Stack
  {
    videoId: "GdXF8rJEm3k",
    category: "mern-stack",
    subCategory: "advanced",
    title: "Complete Full Stack Web Development Preparation : MERN Stack + 6 Major Projects",
    views: "1.8M",
    date: "2024-05-15",
    duration: "10:45:20",
  },
  {
    videoId: "CcFIrllSy2o",
    category: "mern-stack",
    subCategory: "beginner",
    title: "Complete MERN Stack Developer Roadmap for Beginners (2024)",
    views: "950K",
    date: "2024-05-22",
    duration: "0:25:30",
  },
  {
    videoId: "b5mhh5VQfNw",
    category: "mern-stack",
    subCategory: "beginner",
    title: "Mastering MERN as a Beginner | Tanay Pratap #hindi",
    views: "620K",
    date: "2024-05-25",
    duration: "1:15:40",
  },
  {
    videoId: "L_eF8az2cSA",
    category: "mern-stack",
    subCategory: "beginner",
    title: "Mastering MERN as a BEGINNER | Tanay Pratap Hindi",
    views: "580K",
    date: "2024-05-27",
    duration: "1:20:15",
  },

  // Web Development
  {
    videoId: "z0n1aQ3IxWI",
    category: "web-development",
    subCategory: "beginner",
    title: "What is Web Development ? Complete RoadMap from Basics to Advanced | 2023",
    views: "1.5M",
    date: "2024-02-28",
    duration: "0:25:30",
  },
  {
    videoId: "l1EssrLxt7E",
    category: "web-development",
    subCategory: "beginner",
    title: "Introduction to Web Development | World's most premium Web Development Course",
    views: "1.2M",
    date: "2024-03-20",
    duration: "1:30:15",
  },
  {
    videoId: "E_F8MwcVgSA",
    category: "web-development",
    subCategory: "career",
    title: "Frontend Developer Vs. Backend Developer || Salary, Company, Package",
    views: "1.1M",
    date: "2024-05-15",
    duration: "0:15:25",
  },
  {
    videoId: "goK4hKZ742w",
    category: "web-development",
    subCategory: "career",
    title: "FASTEST Web Developer Roadmap 2025 – Job Guarantee?",
    views: "1.1M",
    date: "2024-05-16",
    duration: "0:15:25",
  },
  {
    videoId: "5AhLRjkFeZk",
    category: "web-development",
    subCategory: "career",
    title: "5 Mistakes Beginner Web Developers Make (Avoid These)",
    views: "750K",
    date: "2024-05-18",
    duration: "0:14:15",
  },
  {
    videoId: "vP3TRAsjZss",
    category: "web-development",
    subCategory: "career",
    title: "Front End vs Back End - Which one is good for you ?",
    views: "950K",
    date: "2024-05-27",
    duration: "0:15:25",
  },

  // Syntax and Coding
  {
    videoId: "shoQfc0cJp4",
    category: "syntax-and-coding",
    subCategory: "career",
    title: "Why People Quit Coding? 3 Major Reasons",
    views: "1.2M",
    date: "2024-03-30",
    duration: "0:12:30",
  },
  {
    videoId: "vP2MNhC_Igw",
    category: "syntax-and-coding",
    subCategory: "beginner",
    title: "Stop Trying To Memorize Code - Do This Instead",
    views: "950K",
    date: "2024-04-20",
    duration: "0:10:15",
  },
  {
    videoId: "iH3P3HeF6pE",
    category: "syntax-and-coding",
    subCategory: "career",
    title: "5 Coding Myths | This can save your years",
    views: "850K",
    date: "2024-05-08",
    duration: "0:14:40",
  },
  {
    videoId: "T_wIeJLzdoI",
    category: "syntax-and-coding",
    subCategory: "career",
    title: "3 Signs of an Inexperienced Programmer | Avoid these in Tech",
    views: "720K",
    date: "2024-05-15",
    duration: "0:11:25",
  },
  {
    videoId: "M--A6rBEnNE",
    category: "syntax-and-coding",
    subCategory: "beginner",
    title: "How To Remember Code ? - Explained",
    views: "680K",
    date: "2024-05-22",
    duration: "0:13:50",
  },
  {
    videoId: "nUr0-s_2r48",
    category: "syntax-and-coding",
    subCategory: "beginner",
    title: "How I remember syntax while programming?",
    views: "620K",
    date: "2024-05-25",
    duration: "0:09:30",
  },
  {
    videoId: "FKVf1E78Wb8",
    category: "syntax-and-coding",
    subCategory: "beginner",
    title: "How to make Notes for Coding? Data Structures & Algorithms",
    views: "580K",
    date: "2024-05-27",
    duration: "0:12:45",
  },

  // DevOps
  {
    videoId: "h7LDnVsNRVI",
    category: "devops",
    subCategory: "beginner",
    title: "What is DevOps? DevOps Explained | Simplest Explanation in Hindi",
    views: "950K",
    date: "2024-05-15",
    duration: "0:15:30",
  },
  {
    videoId: "RRBF2YWXFtY",
    category: "devops",
    subCategory: "advanced",
    title: "DevOps Complete Guide for 2025",
    views: "720K",
    date: "2024-05-22",
    duration: "0:25:40",
  },

  // Git & GitHub
  {
    videoId: "Ez8F0nW6S-w",
    category: "git-and-github",
    subCategory: "beginner",
    title: "Complete Git and GitHub Tutorial for Beginners",
    views: "1.8M",
    date: "2024-04-29",
    duration: "2:30:15",
  },

  // Linux
  {
    videoId: "nDXX6LIJx8A",
    category: "linux",
    subCategory: "beginner",
    title: "Is Linux better than Windows?",
    views: "950K",
    date: "2024-05-15",
    duration: "0:15:30",
  },
  {
    videoId: "qOktu4-fkfE",
    category: "linux",
    subCategory: "beginner",
    title: "Download & Install Ubuntu Linux💻 - [2025 New Method🔥]",
    views: "720K",
    date: "2024-05-22",
    duration: "0:20:40",
  },
  {
    videoId: "rrw-Pv3rc0E",
    category: "linux",
    subCategory: "beginner",
    title: "What is LINUX for Beginners? Understand Linux Distributions & Kernel",
    views: "680K",
    date: "2024-05-25",
    duration: "0:18:25",
  },
  {
    videoId: "_tCY-c-sPZc",
    category: "linux",
    subCategory: "beginner",
    title: "Linux Tutorial For Beginners in Hindi",
    views: "620K",
    date: "2024-05-27",
    duration: "1:45:30",
  },
  {
    videoId: "POf5mCs5YgI",
    category: "linux",
    subCategory: "beginner",
    title: "How to Install Ubuntu in 2024 - Quick & Fast",
    views: "580K",
    date: "2024-05-28",
    duration: "0:12:15",
  },

  // Frontend
  {
    videoId: "DbRXv5TXMEE",
    category: "frontend",
    subCategory: "career",
    title: "Front End Developer RoadMap - for Jobs in 2024",
    views: "950K",
    date: "2024-04-30",
    duration: "0:20:40",
  },

  // Wordpress
  {
    videoId: "WK4olrpvW9A",
    category: "wordpress",
    subCategory: "beginner",
    title: "Ultimate WordPress Tutorial 2025: Build Your Site in Just 40 Minutes! 🔥",
    views: "950K",
    date: "2024-04-28",
    duration: "0:40:10",
  },
  {
    videoId: "OkQGYIMkGnE",
    category: "wordpress",
    subCategory: "beginner",
    title: "How to Make a WordPress Website - For Beginners",
    views: "1.2M",
    date: "2024-04-25",
    duration: "0:55:20",
  },
    
  // Backend
  {
    videoId: "gxHXPmePnvo",
    category: "backend",
    subCategory: "advanced",
    title: "🚀🔥 Complete Backend Development in One Day (2025) | Hindi",
    views: "2.1M",
    date: "2024-05-22",
    duration: "8:45:20",
  },
  {
    videoId: "XGa4onZP66Q",
    category: "api",
    subCategory: "beginner",
    title: "What is an API ? Simply Explained",
    views: "1.1M",
    date: "2024-05-08",
    duration: "0:10:15",
  },
  {
    videoId: "WRsKs-K6iII",
    category: "api",
    subCategory: "beginner",
    title: "What is a Rest API? (in 2 Minutes)",
    views: "850K",
    date: "2024-05-15",
    duration: "0:05:30",
  },
  {
    videoId: "UOJZTqA5Loc",
    category: "backend",
    subCategory: "beginner",
    title: "What is SQL? Future Career Scope & Resources",
    views: "650K",
    date: "2024-05-25",
    duration: "0:13:20",
  },

  // DSA
  {
    videoId: "9H_rX1vHuoM",
    category: "dsa",
    subCategory: "career",
    title: "DSA v/s Development | What to do for Placements?",
    views: "890K",
    date: "2024-05-15",
    duration: "0:18:40",
  },
  {
    videoId: "AgyTHzjBS-c",
    category: "dsa",
    subCategory: "career",
    title: "How much Coding to learn for Placements? Data Structure & Algorithms",
    views: "950K",
    date: "2024-05-22",
    duration: "0:14:50",
  },

  // Cybersecurity
  {
    videoId: "WO4M_A_mtBI",
    category: "cybersecurity",
    subCategory: "advanced",
    title: "What is DDOS Attack? How You Can Protect Yourself? | Explained in 5 Minutes",
    views: "380K",
    date: "2024-04-29",
    duration: "0:10:45",
  },
  {
    videoId: "zlZ_dupXxE0",
    category: "cybersecurity",
    subCategory: "advanced",
    title: "How to Hack Password?",
    views: "1.2M",
    date: "2024-05-25",
    duration: "0:11:35",
  },

  // Coding
  {
    videoId: "0HyIda5eub8",
    category: "coding",
    subCategory: "career",
    title: "Learn Coding & Get a Job (in 2025) 🔥",
    views: "1.1M",
    date: "2024-05-22",
    duration: "0:16:25",
  },
  {
    videoId: "koNiEIfo5jY",
    category: "coding",
    subCategory: "career",
    title: "3 Life Saving Websites for Coders!",
    views: "820K",
    date: "2024-05-26",
    duration: "0:10:15",
  },

  // CMS
  {
    videoId: "Tm_vWtMsgOc",
    category: "cms",
    subCategory: "advanced",
    title: "CMS VS Custom Coded Websites",
    views: "380K",
    date: "2024-05-29",
    duration: "0:11:20",
  },

  // Command Prompt
  {
    videoId: "aiZN2ncIItM",
    category: "cmd",
    subCategory: "beginner",
    title: "What is Command Prompt With Full Information? – [Hindi] – Quick Support",
    views: "420K",
    date: "2024-04-30",
    duration: "0:20:15",
  },
  {
    videoId: "Xbmqe0oEfJ0",
    category: "cmd",
    subCategory: "beginner",
    title: "What is the Difference between GUI and CLI or CMD",
    views: "420K",
    date: "2024-05-27",
    duration: "0:12:40",
  },
];